configuration: Release

before_build:
  - nuget restore source/ConfigTransformationTool.sln

build:
  verbosity: minimal

artifacts:
  - path: source\ConfigTransformationTool\bin\$(configuration)\ctt.exe
    name: CttConsole